# Generated by Django 5.0.2 on 2024-03-05 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.CharField(max_length=255)),
                ('download', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcinformation')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_memory', models.CharField(max_length=255)),
                ('used_memory', models.CharField(max_length=255)),
                ('free_memory', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcinformation')),
            ],
        ),
        migrations.CreateModel(
            name='CPUTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.CharField(max_length=255)),
                ('cpu_usage', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcinformation')),
            ],
        ),
        migrations.CreateModel(
            name='StorageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_storage', models.CharField(max_length=255)),
                ('used_storage', models.CharField(max_length=255)),
                ('free_storage', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcinformation')),
            ],
        ),
    ]
