# Generated by Django 5.0.2 on 2024-02-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
