# Generated by Django 5.0.2 on 2024-03-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.CharField(max_length=255)),
                ('cpu_usage', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcinformation')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_memory', models.CharField(max_length=255)),
                ('used_memory', models.CharField(max_length=255)),
                ('free_memory', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcinformation')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.CharField(max_length=255)),
                ('download', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcinformation')),
            ],
        ),
        migrations.CreateModel(
            name='StorageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_storage', models.CharField(max_length=255)),
                ('used_storage', models.CharField(max_length=255)),
                ('free_storage', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcinformation')),
            ],
        ),
    ]
